
#キャンバスを少し小さくする
CANVAS_SMALLER = 0.52

#マウスカーソル
DEFAULT_MOUSE_CURSOR = 'arrow'
MOUSE_CURSOR_LIST = [
    'size_ns',
    'size_ns',
    'size_we',
    'size_we',
    'size_nw_se',
    'size_nw_se',
    'size_ne_sw',
    'size_ne_sw'
]
MOUSE_CURSOR_PIVOT = "fleur"

#myframe関係
NUMBER_IMAGE = 8
MYFRAME_IMAGE_PATH = 'rect.png'
MYFRAME_IMAGE_TAG = 'rect'
MYFRAME_IMAGE_PIVOT_TAG = 'pivot'

#myimage関係
MYIMAGE_MiN_SIZE = 0.1


#mainwindow関係
#キャンバスの大きさ
CANVAS_WIDTH = 1920
CANVAS_HEIGHT = 1080
#枠のサイズを画像より少し大きくする
ADD_FRAME_SIZE = 2.0
#キャンバスを少し大きくする
ADD_CANVAS_SIZE = 15.0
#レベルデータの拡張子
FILE_EXTENSION = '.casl'
#ウィンドウの色
WINDOW_COLOR = 'gray69'
#キャンバスの色
CANVAS_COLOR = 'white'

#マウス座標表示のラベルの位置
LABEL_RELX=0.01 
LABEL_RELY=0.96

#インスペクターウィンドウ？関連
#横幅
INSPECTOR_WIDTH = 200
#縦幅
INSPECTOR_HEIGHT = 400
#位置
INSPECTOR_RELX = 0.8
INSPECTOR_RELY = 0.002
INSPECTOR_STANDARS_POSITION_X = 0
#名前
INSPECTOR_NAME_ADD_Y=0
INSPECTOR_NAME_Y=5+INSPECTOR_NAME_ADD_Y
INSPECTOR_NAME_ENTRY_SIZE_X=33
INSPECTOR_NAME_ENTRY_Y=25+INSPECTOR_NAME_ADD_Y
#座標
INSPECTOR_POSITION_ADD_Y=5
INSPECTOR_POSITION_Y=45+INSPECTOR_POSITION_ADD_Y
INSPECTOR_POSITION_ENTRY_SIZE_X=13
INSPECTOR_POSITION_XY_Y=63+INSPECTOR_POSITION_ADD_Y
INSPECTOR_POSITION_Y_X=110
INSPECTOR_POSITION_ENTRY_Y=68+INSPECTOR_POSITION_ADD_Y
INSPECTOR_POSITION_X_ENTRY_X=20
INSPECTOR_POSITION_Y_ENTRY_X=130
#スケール
INSPECTOR_SCALE_ADD_Y=52
INSPECTOR_SCALE_Y=45+INSPECTOR_SCALE_ADD_Y
INSPECTOR_SCALE_ENTRY_SIZE_X=13
INSPECTOR_SCALE_XY_Y=63+INSPECTOR_SCALE_ADD_Y
INSPECTOR_SCALE_Y_X=110
INSPECTOR_SCALE_ENTRY_Y=68+INSPECTOR_SCALE_ADD_Y
INSPECTOR_SCALE_X_ENTRY_X=20
INSPECTOR_SCALE_Y_ENTRY_X=130
#ピクセル
INSPECTOR_PIXEL_ADD_Y=52
INSPECTOR_PIXEL_Y=95+INSPECTOR_PIXEL_ADD_Y
INSPECTOR_PIXEL_XY_Y=115+INSPECTOR_PIXEL_ADD_Y
INSPECTOR_PIXEL_Y_X=80
#レイヤー優先度
INSPECTOR_LAYER_ADD_Y = 0
INSPECTOR_LAYER_Y= 192
INSPECTOR_LAYER_ENTRY_Y = 215
#ピボット
INSPECTOR_PIVOT_ADD_Y=195
INSPECTOR_PIVOT_Y=45+INSPECTOR_PIVOT_ADD_Y
INSPECTOR_PIVOT_ENTRY_SIZE_X=13
INSPECTOR_PIVOT_XY_Y=63+INSPECTOR_PIVOT_ADD_Y
INSPECTOR_PIVOT_Y_X=110
INSPECTOR_PIVOT_ENTRY_Y=68+INSPECTOR_PIVOT_ADD_Y
INSPECTOR_PIVOT_X_ENTRY_X=20
INSPECTOR_PIVOT_Y_ENTRY_X=130
#ボタン
INSPECTOR_BUTTON_X = 40
INSPECTOR_BUTTON_Y = 300

#プロジェクトウィンドウ？関連
#横幅
PROJECT_WIDTH = 33
#縦幅
PROJECT_HEIGHT = 15
#位置
PROJECT_RELY = 0.5177